### ISSUE TITLE
stream.Read return value is ignored

### ISSUE THREAD

**Issue by tshcherban** [uranium62/xxHash#1]
https://github.com/uranium62/xxHash/blob/f5d67a126dacda0443eff73cdd884501f8f3708b/src/Standart.Hash.xxHash/xxHash64.Stream.cs#L59
There might be an issue if `stream.read` returned less than `bufferSize` (e.g. `NetworkStream`), invalid hash is calculated.

**Comment by uranium62** [comment]
Hi @tshcherban 
Thank you very much for this issue. 
I am going to rewrite the stream implementation using pipes and fix the bug.
Your raised very serious problem about it I have never thought before

**Comment by uranium62** [comment]
Fixed
