### ISSUE TITLE
Is the implementation only works on the X64 machines?

### ISSUE THREAD

**Issue by moien007** [uranium62/xxHash#10]
Hi,

In the README.md there's camo which saying
> **platform x64** 

at https://github.com/uranium62/xxHash/blame/master/README.md#L20-L22.

Is this library only limited to the X64 architectures?

**Comment by uranium62** [comment]
By default, I compile it only for x64 architecture. For x64 architecture, registers are bigger and we get maximum performance.

**Comment by uranium62** [comment]
But you can compile it for x86 architecture
