### ISSUE TITLE
XXH3 and .NET 5 Compatibility

### ISSUE THREAD

**Issue by VoidMonk** [uranium62/xxHash#11]
Thanks for sharing this cool implementation. It performs faster than some other xxHash C# libraries I tested, like [HashDepot](https://github.com/ssg/HashDepot), specially for long strings.

Do you have any plans to keep it up-to-date with [XXH3](https://github.com/Cyan4973/xxHash#benchmarks), and .NET 5 besides the current .NET Standard 2.0 compatibility as it seems like .NET Standard may be retired?

**Comment by uranium62** [comment]
Thanks for the feedback.
This is one of my side projects and sometimes it's hard to find time for it.

Yes, I have a plan to add XXH3 and XXH128  with SSE instructions.
But I don't know when I'll do it. I'll try to do it before the New Year. But I don't promise.

And yes, I'll migrate it to the .NET Standard 2.1

**Comment by voltagex** [comment]
Hi @uranium62, just checking if you've had a chance to look at this. The https://github.com/starburst997/xxHash seems to have added NET 5 support (although I think this is just a version bump, no code changes?)

**Comment by uranium62** [comment]
.Net Standard 2.1 doesn't support https://github.com/dotnet/standard/issues/1094.
I ported xxHash128 with support SIMD instructions but only for net6.0

**Comment by uranium62** [comment]
XXH3 is ready too
