### ISSUE TITLE
Not supporting in >NET 4.5 version

### ISSUE THREAD

**Issue by gauravkoradiya** [uranium62/xxHash#12]
It is not supporting 4.5 version of .NET. it will be great help if it is made consistant with version.

Right now i can see my console with below error:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Standart.Hash.xxHash 3.1.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.	
```

**Comment by sgf** [comment]
@uranium62 hello,could you add [ .net 5], [.net 6] support ? i think that's will be easy.

**Comment by uranium62** [comment]
Currently, I'm going to support only .net 6.0 (LTS). More details you can read in this [thread](https://github.com/uranium62/xxHash/issues/18).
