### ISSUE TITLE
Sign assembly with strong name

### ISSUE THREAD

**Issue by satfx** [uranium62/xxHash#13]
Please consider to add a strong name to this assembly, so it can be consumed as a dependency from another signed assembly.

Thank you in advance!

**Comment by uranium62** [comment]
Thanks for the feedback @satfx ,
I improved performance more ( added AVX instructions, add some intistics), but unfortunately I don't have so much time to finish this work

In the near future, I will try to finish everything and publish it, if it is very urgent for you, I can quickly publish the signed package for you.

sorry for it

**Comment by satfx** [comment]
Thanks for a quick reply, @uranium62.

No, it is absolutely not urgent and required right here and right now in comparison with performance tunings you mention. I'm able to do it by myself, but please don't forget about it for the future releases.

And thank you very much for you work and that great lib!

**Comment by uranium62** [comment]
Sorry I'll do it)))

**Comment by uranium62** [comment]
Done: https://www.nuget.org/packages/Standart.Hash.xxHash.Signed
