### ISSUE TITLE
Please sign the assembly with a strong name (snk)

### ISSUE THREAD

**Issue by QuanosSolutions** [uranium62/xxHash#16]
Hi,

We do have a lib using your lib and ours is strong named, which produces a warning because yours isn't.

Thank you very much :-)

**Comment by Scordo** [comment]
I've created a pull-request for this: https://github.com/uranium62/xxHash/pull/17

**Comment by Scordo** [comment]
Make sure to choose a new major-version for the package before publishing it.

**Comment by uranium62** [comment]
in process

**Comment by uranium62** [comment]
Done: https://www.nuget.org/packages/Standart.Hash.xxHash.Signed

I did it manually. Please create a pull request and add steps to the release.yml (Github actions). Do it all automatically
