### ISSUE TITLE
.Net Standard 2.1

### ISSUE THREAD

**Issue by artelk** [uranium62/xxHash#18]
Hello,
The nuget package is only available for .Net 6 projects.
Please change the target framework to .Net Standard 2.1 so other libraries targeting to .Net Standard 2.1 could use that.

**Comment by uranium62** [comment]
.Net Standard 2.1 doesn't support [SIMD instructions](https://github.com/dotnet/standard/issues/1094).
I was faced with the choice of building the library using netstandard2.1 or SIMD. I chose the second one.
