### ISSUE TITLE
Support ReadOnlySpan

### ISSUE THREAD

**Issue by JohnNilsson** [uranium62/xxHash#2]
First of all, awesome lib, in my test is was about a magnitude faster than another implementation I was evaluating!

Would you consider adding, or changing the api, to support ReadOnlySpan?

Did this to get around it for the moment, not particularly pretty though.
```csharp
      var span = new Span<byte>(Unsafe.AsPointer(ref MemoryMarshal.GetReference(roSpan)), roSpan.Length);
      return (int)xxHash32.ComputeHash(span, span.Length);
```

**Comment by uranium62** [comment]
Hi John,
Thank you for good words. You are right. 
But what about backward compatibility?

It was my mistake to add Spаn instead ReadOnlySpan
I think I will add one addition API for ReadOnlySpan

**Comment by uranium62** [comment]
@JohnNilsson  I have added support ReadOnlySpan.
Thank you for your proposal.

**Comment by JohnNilsson** [comment]
Sweet!
Thanks again!
