### ISSUE TITLE
C Test Harness

### ISSUE THREAD

**Issue by cocowalla** [uranium62/xxHash#4]
Firstly, thanks for this excellent library!

In the readme you provide comparison against the reference C code, but I can't find any C project in this repo - is it possible to publish the test harness you used to create these benchmarks?

**Comment by uranium62** [comment]
Hi @cocowalla ,

I have a separate branch for it (https://github.com/uranium62/xxHash/tree/native)
You can look benchmarks in the branch

**Comment by cocowalla** [comment]
Ah, so you compared vs PInvoke'ing into a C implementation, rather than the "raw" C version - thanks!
