### ISSUE TITLE
Fast array/span access without `fixed` nor pinning

### ISSUE THREAD

**Issue by NickStrupat** [uranium62/xxHash#6]
Hi @uranium62 ,

Thanks for your work on this library. It's the only one I found that is allocation-free. I'm wondering if there's room for GC performance improvement by removing the `fixed` pinning and using this technique instead? What do you think?

https://ndportmann.com/system-runtime-compilerservices-unsafe/

**Comment by moien007** [comment]
@NickStrupat Is pinning concerned even when a computation is fast?

**Comment by uranium62** [comment]
I am very embarrassed that I am only now answering.
I can try to use this approach but don't think I'll have performance improvement.

But let's try.

**Comment by uranium62** [comment]
my experiments have shown that there is no noticeable gain in performance.
