### ISSUE TITLE
Mismatch between a line of code and its comment

### ISSUE THREAD

**Issue by moien007** [uranium62/xxHash#9]
Hi,

I'm concerned about this line of code and its comment,
https://github.com/uranium62/xxHash/blob/b7662afc704d223f75c855807eba14b12c090fe6/src/Standart.Hash.xxHash/xxHash64.Unsafe.cs#L256
Where 23 != 27.

Which value is the right one to choose to be compatible with other implementations?

**Comment by uranium62** [comment]
The comment is incorrect (typo). It should be 
```
h64 = BitUtils.RotateLeft(h64, 23) * p2 + p3; // (rotl 23) * p2 + p3 
```
But the implementation is correct
https://github.com/Cyan4973/xxHash/blob/dev/xxhash.h#L1618

**Comment by uranium62** [comment]
I fixed it
